// Generated by packages/deploy-schema/scripts/generate-types.mjs from schema/v2/deployment.schema.json.
// Do not edit by hand.

export type DeploymentKind = 'service' | 'worker' | 'cron' | 'job' | 'model' | 'static';
export type DeploymentBuildStrategy = 'dockerfile' | 'buildpack' | 'static' | 'none';
export type DeploymentLanguage = 'javascript' | 'typescript' | 'python' | 'php' | 'go';
export type DeploymentExposure = 'none' | 'internal' | 'public';
export type DeploymentScalingMode = 'none' | 'hpa' | 'keda';
export type DeploymentMetricType =
  'cpu' | 'memory' | 'rps' | 'rabbitmq' | 'sqs' | 'pubsub' | 'redis' | 'kafka' | 'nats' | 'external' | 'keda';

export type DeploymentSha256Digest = `sha256:${string}`;

export type DeploymentImageReference =
  | {
      repository: string;
      tag: string;
      digest?: DeploymentSha256Digest;
    }
  | {
      repository: string;
      digest: DeploymentSha256Digest;
      tag?: string;
    };

export interface DeploymentBuildSpec {
  strategy: DeploymentBuildStrategy;
  context?: string;
  dockerfile?: string;
  script?: string;
  output?: string;
  image?: DeploymentImageReference;
}

export interface DeploymentRuntimeSpec {
  language: DeploymentLanguage;
  framework?: string;
  command: string[];
  workingDirectory?: string;
  cron?: string;
  tuning?: Record<string, string>;
}

export interface DeploymentPort {
  name: string;
  containerPort: number;
  servicePort?: number;
  protocol?: 'TCP' | 'UDP';
}

export interface DeploymentRoute {
  host?: string;
  path: string;
  pathType?: 'Exact' | 'Prefix' | 'ImplementationSpecific';
  tlsSecretRef?: string;
}

export interface DeploymentNetworkSpec {
  exposure?: DeploymentExposure;
  ports?: DeploymentPort[];
  routes?: DeploymentRoute[];
}

export interface DeploymentProbe {
  type: 'http' | 'tcp' | 'exec';
  path?: string;
  port?: number | string;
  command?: string[];
  delaySeconds?: number;
  periodSeconds?: number;
  timeoutSeconds?: number;
  failureThreshold?: number;
  successThreshold?: number;
}

export interface DeploymentProbesSpec {
  startup?: DeploymentProbe;
  readiness?: DeploymentProbe;
  liveness?: DeploymentProbe;
}

export interface DeploymentSecretRef {
  name: string;
  provider?: string;
  key?: string;
  target?: string;
  optional?: boolean;
}

export interface DeploymentEnvironmentSpec {
  values?: Record<string, string>;
  secretRefs?: DeploymentSecretRef[];
}

export interface DeploymentResourceQuantity {
  cpu?: string;
  memory?: string;
  ephemeralStorage?: string;
}

export interface DeploymentAccelerator {
  type: string;
  count: number;
  model?: string;
}

export interface DeploymentResourcesSpec {
  requests?: DeploymentResourceQuantity;
  limits?: DeploymentResourceQuantity;
  accelerators?: DeploymentAccelerator[];
}

export interface DeploymentStorage {
  name: string;
  type: 'ephemeral' | 'persistent' | 'secret' | 'config';
  mountPath: string;
  size?: string;
  className?: string;
  readOnly?: boolean;
  sourceRef?: string;
}

export interface DeploymentIdentitySpec {
  serviceAccount?: string;
  providerRoleRef?: string;
  workloadIdentity?: string;
  automountServiceAccountToken?: false;
}

export interface DeploymentTelemetrySignal {
  enabled: boolean;
}

export interface DeploymentTelemetryMetrics {
  enabled: boolean;
  path?: string;
  port?: number;
}

export interface DeploymentTelemetrySpec {
  metrics?: DeploymentTelemetryMetrics;
  traces?: DeploymentTelemetrySignal;
  logs?: DeploymentTelemetrySignal;
}

export interface DeploymentDrainSpec {
  enabled: boolean;
  timeoutSeconds?: number;
}

export interface DeploymentLifecycleSpec {
  terminationGracePeriodSeconds?: number;
  preStopCommand?: string[];
  drain?: DeploymentDrainSpec;
}

export interface DeploymentScalingMetricFields {
  target: number;
  sourceRef?: string;
  query?: string;
  route?: string;
  queue?: string;
  topic?: string;
  stream?: string;
  consumerGroup?: string;
  metricName?: string;
  scaler?: string;
  metadata?: Record<string, string>;
  authenticationRef?: string;
}

export type DeploymentScalingMetric =
  | (DeploymentScalingMetricFields & { type: 'cpu' | 'memory' })
  | (DeploymentScalingMetricFields & {
      type: 'rps';
      sourceRef: string;
      query: string;
    })
  | (DeploymentScalingMetricFields & {
      type: 'rabbitmq' | 'sqs' | 'pubsub' | 'redis' | 'kafka' | 'nats';
      sourceRef: string;
    })
  | (DeploymentScalingMetricFields & {
      type: 'external';
      sourceRef: string;
      metricName: string;
    })
  | (DeploymentScalingMetricFields & {
      type: 'keda';
      scaler: string;
    });

export interface DeploymentScalingBehavior {
  scaleUpStabilizationSeconds?: number;
  scaleDownStabilizationSeconds?: number;
}

export interface DeploymentScalingFallback {
  replicas: number;
  failureThreshold: number;
}

export interface DeploymentScalingSpec {
  mode: DeploymentScalingMode;
  minReplicas?: number;
  maxReplicas?: number;
  pollingInterval?: number;
  cooldownPeriod?: number;
  metrics?: DeploymentScalingMetric[];
  behavior?: DeploymentScalingBehavior;
  fallback?: DeploymentScalingFallback;
}

export interface DeploymentKubernetesToleration {
  key: string;
  operator?: string;
  value?: string;
  effect?: string;
}

export interface DeploymentKubernetesOverrides {
  namespace?: string;
  serviceAccountName?: string;
  nodeSelector?: Record<string, string>;
  tolerations?: DeploymentKubernetesToleration[];
}

export interface DeploymentPm2Overrides {
  instances?: number;
  execMode?: 'fork' | 'cluster';
}

export interface DeploymentCoolifyOverrides {
  serverId?: string;
  destinationId?: string;
  domain?: string;
}

export interface DeploymentStaticOverrides {
  bucket?: string;
  cdn?: string;
}

export interface DeploymentAdapterOverrides {
  kubernetes?: DeploymentKubernetesOverrides;
  pm2?: DeploymentPm2Overrides;
  coolify?: DeploymentCoolifyOverrides;
  static?: DeploymentStaticOverrides;
}

export type MergePatch<T> = {
  [Key in keyof T]?: NonNullable<T[Key]> extends readonly unknown[]
    ? NonNullable<T[Key]> | null
    : NonNullable<T[Key]> extends object
      ? MergePatch<NonNullable<T[Key]>> | null
      : T[Key] | null;
};

export type DeploymentPatchableSpecV2 = Omit<
  DeploymentSpecV2,
  | '$schema'
  | 'schemaVersion'
  | 'enabled'
  | 'id'
  | 'kind'
  | 'profile'
  | 'build'
  | 'runtime'
  | 'variants'
  | 'environments'
> & {
  build: Omit<DeploymentBuildSpec, 'strategy'>;
  runtime: Omit<DeploymentRuntimeSpec, 'language'>;
};

export type DeploymentObjectPatchV2 = MergePatch<DeploymentPatchableSpecV2>;
export type DeploymentPatchV2 = DeploymentObjectPatchV2 | null;
export type DeploymentVariantPatchV2 = DeploymentObjectPatchV2 & {
  environments?: Record<string, DeploymentPatchV2>;
};

export interface DeploymentSpecV2 {
  $schema?: string;
  schemaVersion: '2';
  enabled: boolean;
  id: string;
  kind: DeploymentKind;
  profile?: string;
  suspended?: boolean;
  labels?: Record<string, string>;
  build: DeploymentBuildSpec;
  runtime: DeploymentRuntimeSpec;
  network?: DeploymentNetworkSpec;
  probes?: DeploymentProbesSpec;
  env?: DeploymentEnvironmentSpec;
  resources?: DeploymentResourcesSpec;
  storage?: DeploymentStorage[];
  identity?: DeploymentIdentitySpec;
  telemetry?: DeploymentTelemetrySpec;
  lifecycle?: DeploymentLifecycleSpec;
  scaling?: DeploymentScalingSpec;
  variants?: Record<string, DeploymentVariantPatchV2>;
  environments?: Record<string, DeploymentPatchV2>;
  adapterOverrides?: DeploymentAdapterOverrides;
}

export type DeploymentRequiredFields = Pick<
  DeploymentSpecV2,
  'schemaVersion' | 'enabled' | 'id' | 'kind' | 'build' | 'runtime'
>;

// Compatibility aliases retained for the 0.2 public surface.
export type DeploymentBuild = DeploymentBuildSpec;
export type DeploymentRuntime = DeploymentRuntimeSpec;
export type DeploymentNetwork = DeploymentNetworkSpec;
export type DeploymentScaling = DeploymentScalingSpec;
