// Generated by packages/deploy-schema/scripts/generate-types.mjs from schemas/v2/monox.schema.json.
// Do not edit by hand.

export type TargetProvider = 'generic' | 'aws' | 'gcp';
export type TargetProvisioner = 'none' | 'pulumi';
export type TargetTransport = 'local' | 'ssh' | 'aws-ssm' | 'gcp-iap' | 'coolify-api' | 'kubernetes-api';
export type TargetRuntime = 'pm2' | 'docker' | 'coolify' | 'kubernetes' | 'static';

export interface MonoXConfigRequiredFields {
  schemaVersion: '2';
  project: unknown;
  boundaries: unknown;
  workloadProfiles: unknown;
  environments: unknown;
  targets: unknown;
  addons: unknown;
}
