import { readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const packageRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const repositoryRoot = path.resolve(packageRoot, '../..');

function literal(value) {
  return JSON.stringify(value).replaceAll('"', "'");
}

function union(values) {
  return values.map(literal).join(' | ');
}

function header(source) {
  return `// Generated by packages/deploy-schema/scripts/generate-types.mjs from ${source}.\n// Do not edit by hand.\n\n`;
}

function assertSchema(condition, message) {
  if (!condition) throw new TypeError(`Unsupported deployment schema shape: ${message}`);
}

function propertyName(name) {
  return /^[$A-Z_a-z][$\w]*$/.test(name) ? name : JSON.stringify(name);
}

const referenceTypes = Object.freeze({
  '#/$defs/id': 'string',
  '#/$defs/nonEmptyStringArray': 'string[]',
  '#/$defs/port': 'number',
  '#/$defs/probe': 'DeploymentProbe',
  '#/$defs/quantity': 'string',
  '#/$defs/resourceQuantity': 'DeploymentResourceQuantity',
  '#/$defs/scalingMetric': 'DeploymentScalingMetric',
  '#/$defs/stringArray': 'string[]',
  '#/$defs/stringMap': 'Record<string, string>',
  '#/$defs/telemetrySignal': 'DeploymentTelemetrySignal',
});

function objectType(schema) {
  const properties = schema.properties ?? {};
  const required = new Set(schema.required ?? []);
  const fields = Object.entries(properties).map(
    ([name, value]) => `${propertyName(name)}${required.has(name) ? '' : '?'}: ${schemaType(value)};`
  );
  if (fields.length > 0) return `{ ${fields.join(' ')} }`;
  if (schema.additionalProperties && typeof schema.additionalProperties === 'object') {
    return `Record<string, ${schemaType(schema.additionalProperties)}>`;
  }
  return 'Record<string, unknown>';
}

function schemaType(schema) {
  assertSchema(schema && typeof schema === 'object', 'expected a schema object');
  if (schema.$ref) {
    const type = referenceTypes[schema.$ref];
    assertSchema(type, `unmapped reference ${schema.$ref}`);
    return type;
  }
  if (Object.hasOwn(schema, 'const')) return literal(schema.const);
  if (schema.enum) return union(schema.enum);
  if (schema.oneOf) return schema.oneOf.map(schemaType).join(' | ');
  if (schema.anyOf && !schema.type) return schema.anyOf.map(schemaType).join(' | ');
  if (Array.isArray(schema.type))
    return schema.type.map((type) => schemaType({ ...schema, type })).join(' | ');
  if (schema.type === 'string') {
    return schema.pattern === '^sha256:[a-f0-9]{64}$' ? 'DeploymentSha256Digest' : 'string';
  }
  if (schema.type === 'integer' || schema.type === 'number') return 'number';
  if (schema.type === 'boolean') return 'boolean';
  if (schema.type === 'null') return 'null';
  if (schema.type === 'array') return `Array<${schemaType(schema.items)}>`;
  if (schema.type === 'object' || schema.properties || schema.additionalProperties) return objectType(schema);
  throw new TypeError(`Unsupported deployment schema node: ${JSON.stringify(schema)}`);
}

function renderInterface(name, schema, overrides = {}) {
  assertSchema(schema.type === 'object', `${name} must be an object`);
  const required = new Set(schema.required ?? []);
  const lines = Object.entries(schema.properties ?? {}).map(([property, value]) => {
    const type = overrides[property] ?? schemaType(value);
    return `  ${propertyName(property)}${required.has(property) ? '' : '?'}: ${type};`;
  });
  return `export interface ${name} {\n${lines.join('\n')}\n}\n`;
}

function renderImageReference(imageSchema) {
  const properties = imageSchema.properties;
  assertSchema(imageSchema.required?.includes('repository'), 'image.repository must remain required');
  const choices = new Set((imageSchema.anyOf ?? []).flatMap((choice) => choice.required ?? []));
  assertSchema(
    choices.size === 2 && choices.has('tag') && choices.has('digest'),
    'image needs tag or digest'
  );
  return `export type DeploymentSha256Digest = \`sha256:\${string}\`;

export type DeploymentImageReference =
  | {
      repository: ${schemaType(properties.repository)};
      tag: ${schemaType(properties.tag)};
      digest?: ${schemaType(properties.digest)};
    }
  | {
      repository: ${schemaType(properties.repository)};
      digest: ${schemaType(properties.digest)};
      tag?: ${schemaType(properties.tag)};
    };
`;
}

function renderScalingMetric(metricSchema) {
  const metricTypes = metricSchema.properties.type.enum;
  const groups = {
    native: ['cpu', 'memory'],
    rps: ['rps'],
    sourced: ['rabbitmq', 'sqs', 'pubsub', 'redis', 'kafka', 'nats'],
    external: ['external'],
    keda: ['keda'],
  };
  const represented = Object.values(groups).flat().sort();
  assertSchema(
    JSON.stringify(represented) === JSON.stringify([...metricTypes].sort()),
    'scaling metric union must classify every enum value exactly once'
  );
  const fields = {
    ...metricSchema,
    required: metricSchema.required.filter((name) => name !== 'type'),
    properties: Object.fromEntries(
      Object.entries(metricSchema.properties).filter(([name]) => name !== 'type')
    ),
  };
  return `${renderInterface('DeploymentScalingMetricFields', fields)}
export type DeploymentScalingMetric =
  | (DeploymentScalingMetricFields & { type: ${union(groups.native)} })
  | (DeploymentScalingMetricFields & {
      type: ${union(groups.rps)};
      sourceRef: string;
      query: string;
    })
  | (DeploymentScalingMetricFields & {
      type: ${union(groups.sourced)};
      sourceRef: string;
    })
  | (DeploymentScalingMetricFields & {
      type: ${union(groups.external)};
      sourceRef: string;
      metricName: string;
    })
  | (DeploymentScalingMetricFields & {
      type: ${union(groups.keda)};
      scaler: string;
    });
`;
}

export function renderDeploymentGeneratedTypes(schema) {
  const properties = schema.properties;
  const network = properties.network.properties;
  const telemetry = properties.telemetry.properties;
  const lifecycle = properties.lifecycle.properties;
  const scaling = properties.scaling.properties;
  const adapterOverrides = properties.adapterOverrides.properties;
  const resourceProperties = properties.resources.properties;
  const blocks = [
    `${header('schema/v2/deployment.schema.json')}export type DeploymentKind = ${union(properties.kind.enum)};
export type DeploymentBuildStrategy = ${union(properties.build.properties.strategy.enum)};
export type DeploymentLanguage = ${union(properties.runtime.properties.language.enum)};
export type DeploymentExposure = ${union(network.exposure.enum)};
export type DeploymentScalingMode = ${union(scaling.mode.enum)};
export type DeploymentMetricType = ${union(schema.$defs.scalingMetric.properties.type.enum)};
`,
    renderImageReference(properties.build.properties.image),
    renderInterface('DeploymentBuildSpec', properties.build, {
      strategy: 'DeploymentBuildStrategy',
      image: 'DeploymentImageReference',
    }),
    renderInterface('DeploymentRuntimeSpec', properties.runtime, {
      language: 'DeploymentLanguage',
    }),
    renderInterface('DeploymentPort', network.ports.items),
    renderInterface('DeploymentRoute', network.routes.items),
    renderInterface('DeploymentNetworkSpec', properties.network, {
      exposure: 'DeploymentExposure',
      ports: 'DeploymentPort[]',
      routes: 'DeploymentRoute[]',
    }),
    renderInterface('DeploymentProbe', schema.$defs.probe),
    renderInterface('DeploymentProbesSpec', properties.probes),
    renderInterface('DeploymentSecretRef', properties.env.properties.secretRefs.items),
    renderInterface('DeploymentEnvironmentSpec', properties.env, {
      secretRefs: 'DeploymentSecretRef[]',
    }),
    renderInterface('DeploymentResourceQuantity', schema.$defs.resourceQuantity),
    renderInterface('DeploymentAccelerator', resourceProperties.accelerators.items),
    renderInterface('DeploymentResourcesSpec', properties.resources, {
      accelerators: 'DeploymentAccelerator[]',
    }),
    renderInterface('DeploymentStorage', properties.storage.items),
    renderInterface('DeploymentIdentitySpec', properties.identity),
    renderInterface('DeploymentTelemetrySignal', schema.$defs.telemetrySignal),
    renderInterface('DeploymentTelemetryMetrics', telemetry.metrics),
    renderInterface('DeploymentTelemetrySpec', properties.telemetry, {
      metrics: 'DeploymentTelemetryMetrics',
    }),
    renderInterface('DeploymentDrainSpec', lifecycle.drain),
    renderInterface('DeploymentLifecycleSpec', properties.lifecycle, {
      drain: 'DeploymentDrainSpec',
    }),
    renderScalingMetric(schema.$defs.scalingMetric),
    renderInterface('DeploymentScalingBehavior', scaling.behavior),
    renderInterface('DeploymentScalingFallback', scaling.fallback),
    renderInterface('DeploymentScalingSpec', properties.scaling, {
      mode: 'DeploymentScalingMode',
      metrics: 'DeploymentScalingMetric[]',
      behavior: 'DeploymentScalingBehavior',
      fallback: 'DeploymentScalingFallback',
    }),
    renderInterface(
      'DeploymentKubernetesToleration',
      adapterOverrides.kubernetes.properties.tolerations.items
    ),
    renderInterface('DeploymentKubernetesOverrides', adapterOverrides.kubernetes, {
      tolerations: 'DeploymentKubernetesToleration[]',
    }),
    renderInterface('DeploymentPm2Overrides', adapterOverrides.pm2),
    renderInterface('DeploymentCoolifyOverrides', adapterOverrides.coolify),
    renderInterface('DeploymentStaticOverrides', adapterOverrides.static),
    renderInterface('DeploymentAdapterOverrides', properties.adapterOverrides, {
      kubernetes: 'DeploymentKubernetesOverrides',
      pm2: 'DeploymentPm2Overrides',
      coolify: 'DeploymentCoolifyOverrides',
      static: 'DeploymentStaticOverrides',
    }),
    `export type MergePatch<T> = {
  [Key in keyof T]?: NonNullable<T[Key]> extends readonly unknown[]
    ? NonNullable<T[Key]> | null
    : NonNullable<T[Key]> extends object
      ? MergePatch<NonNullable<T[Key]>> | null
      : T[Key] | null;
};

export type DeploymentPatchableSpecV2 = Omit<
  DeploymentSpecV2,
  | '$schema'
  | 'schemaVersion'
  | 'enabled'
  | 'id'
  | 'kind'
  | 'profile'
  | 'build'
  | 'runtime'
  | 'variants'
  | 'environments'
> & {
  build: Omit<DeploymentBuildSpec, 'strategy'>;
  runtime: Omit<DeploymentRuntimeSpec, 'language'>;
};

export type DeploymentObjectPatchV2 = MergePatch<DeploymentPatchableSpecV2>;
export type DeploymentPatchV2 = DeploymentObjectPatchV2 | null;
export type DeploymentVariantPatchV2 = DeploymentObjectPatchV2 & {
  environments?: Record<string, DeploymentPatchV2>;
};
`,
    renderInterface('DeploymentSpecV2', schema, {
      kind: 'DeploymentKind',
      build: 'DeploymentBuildSpec',
      runtime: 'DeploymentRuntimeSpec',
      network: 'DeploymentNetworkSpec',
      probes: 'DeploymentProbesSpec',
      env: 'DeploymentEnvironmentSpec',
      resources: 'DeploymentResourcesSpec',
      storage: 'DeploymentStorage[]',
      identity: 'DeploymentIdentitySpec',
      telemetry: 'DeploymentTelemetrySpec',
      lifecycle: 'DeploymentLifecycleSpec',
      scaling: 'DeploymentScalingSpec',
      variants: 'Record<string, DeploymentVariantPatchV2>',
      environments: 'Record<string, DeploymentPatchV2>',
      adapterOverrides: 'DeploymentAdapterOverrides',
    }),
    `export type DeploymentRequiredFields = Pick<
  DeploymentSpecV2,
  ${schema.required.map(literal).join(' | ')}
>;

// Compatibility aliases retained for the 0.2 alpha public surface.
export type DeploymentBuild = DeploymentBuildSpec;
export type DeploymentRuntime = DeploymentRuntimeSpec;
export type DeploymentNetwork = DeploymentNetworkSpec;
export type DeploymentScaling = DeploymentScalingSpec;
`,
  ];
  return blocks.join('\n');
}

export function renderConfigGeneratedTypes(schema) {
  const target = schema.$defs.target.properties;
  return `${header('schemas/v2/monox.schema.json')}export type TargetProvider = ${union(target.provider.enum)};
export type TargetProvisioner = ${union(target.provisioner.enum)};
export type TargetTransport = ${union(target.transport.enum)};
export type TargetRuntime = ${union(target.runtime.enum)};

export interface MonoXConfigRequiredFields {
${schema.required
  .map((name) => (name === 'schemaVersion' ? `  ${name}: '2';` : `  ${name}: unknown;`))
  .join('\n')}
}
`;
}

export async function generatedTypeFiles() {
  const { format } = await import('prettier');
  const deploymentSchema = JSON.parse(
    await readFile(path.join(packageRoot, 'schema/v2/deployment.schema.json'), 'utf8')
  );
  const configSchema = JSON.parse(
    await readFile(path.join(repositoryRoot, 'schemas/v2/monox.schema.json'), 'utf8')
  );
  return [
    {
      path: path.join(packageRoot, 'src/generated.d.ts'),
      content: await format(renderDeploymentGeneratedTypes(deploymentSchema), {
        parser: 'typescript',
        printWidth: 110,
        singleQuote: true,
        trailingComma: 'es5',
      }),
    },
    {
      path: path.join(repositoryRoot, 'packages/config/src/generated.d.ts'),
      content: await format(renderConfigGeneratedTypes(configSchema), {
        parser: 'typescript',
        printWidth: 110,
        singleQuote: true,
        trailingComma: 'es5',
      }),
    },
  ];
}

async function main(argument) {
  const files = await generatedTypeFiles();
  if (argument === '--write') {
    await Promise.all(files.map((file) => writeFile(file.path, file.content, 'utf8')));
    return;
  }
  if (argument !== '--check') throw new TypeError('Usage: generate-types.mjs --check|--write');
  const stale = [];
  for (const file of files) {
    const current = await readFile(file.path, 'utf8').catch(() => '');
    if (current !== file.content) stale.push(path.relative(repositoryRoot, file.path));
  }
  if (stale.length) throw new Error(`Generated type files are stale: ${stale.join(', ')}`);
}

const isEntryPoint = process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url);
if (isEntryPoint) {
  main(process.argv[2]).catch((error) => {
    process.stderr.write(`${error.message}\n`);
    process.exitCode = 1;
  });
}
